# AUTOGENERATED FROM 'tests/fixture.edgeql' WITH:
#     $ edgedb-py
from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class FixtureResult(NoPydanticValidation):
    id: uuid.UUID


async def fixture(
        executor: edgedb.AsyncIOExecutor,
) -> FixtureResult:
    return await executor.query_single(
        """\
        insert User {name := 'Jonathan Harker'};
        insert User {name := 'Count Dracula'};
        insert User {name := 'Mina Murray'};
        insert Event {
          name := 'Resuscitation',
          host := (select User filter .name = 'Mina Murray'),
          address := 'Britain',
          schedule := <datetime>'1889-07-28T06:59:59+00:00'
        };\
        """,
    )
